### ISSUE TITLE
KSwitch does not support non-vanilla items

### ISSUE THREAD

**Issue by Shadowdragon019** [Snownee/Kiwi#77]
### Project

KSwitch

### Mod loader

Forge

### Minecraft version

1.20.1

### Mod version

0.0.2

### Modloader version

Forge 47.4.0

### Modpack info

Custom wip modpack

### [IMPORTANT] If bug:

- [x] I have confirmed this bug is reproducible on a minimal setup, not a modpack with many other mods.

### [IMPORTANT] If bug: The **latest.log** file, not the crash report

https://mclo.gs/xPVeM9h

### Issue description

I made a
```yaml
switch:
    enabled: true
    cascading: true
blocks:
    - "minecraft:dirt"
    - "waystones:waystone"
    - "waystones:mossy_waystone"
```
I have waystones installed because to get some non-vanilla blocks in. I also tried it with farmers delight & sophisticted backpacks to the same effects.
I also restarting Minecraft after applying the changes.
I selected dirt & all I got was dirt
